### ISSUE TITLE
Accent Characters for Username not showing poperly

### ISSUE THREAD

**Issue by filiy** [BCDevOps/platform-services#10]
This is showing up in SSO and in Rocket Chat.

KeyCloak
![image](https://user-images.githubusercontent.com/24232206/50714615-59a47180-102e-11e9-8152-ae1f63232c97.png)

RocketChat
![image](https://user-images.githubusercontent.com/24232206/50714729-c91a6100-102e-11e9-8c7c-661b352012d6.png)

**Comment by filiy** [comment]
I believe this is a SSO/KeyCloak thing as I can put in accent characters into rocket chat manually:

![image](https://user-images.githubusercontent.com/24232206/51001527-2d349d80-14e5-11e9-81bd-c703e05ffe3a.png)

Username may not allow accent characters until this PR is merged.
https://github.com/RocketChat/Rocket.Chat/pull/9914

**Comment by filiy** [comment]
This is strictly a keycloak thing i believe.

**Comment by filiy** [comment]
Maybe @cvarjao and @ShellyXueHan have come across this, or know how to fix?

**Comment by filiy** [comment]
@ShellyXueHan Can you look into this?

**Comment by ShellyXueHan** [comment]
I couldn't find a way to fix it right now, might be solved during next upgrade. @cvarjao what do you think? For now the keycloak profile editing page is mandatory for all users to rocket.chat, where they get to update first and last name to recognized English words.

**Comment by ShellyXueHan** [comment]
This issue has been fixed with the 7.3 upgrade.
For example here:
![Screen Shot 2019-09-18 at 11.39.42 AM.png](https://images.zenhubusercontent.com/5c1acc79305b926f81e2c3d4/f5f63a4d-b3b2-492e-be85-73014419c836)

Closing.
