### ISSUE TITLE
Patroni Cluster unable to recover when all pods go offline

### ISSUE THREAD

**Issue by jujaga** [BCDevOps/platform-services#127]
If and when an entire Patroni cluster is knocked offline at the same time (i.e. all 3 Patroni pods crash out at the same time), the cluster hangs and is unable to self-recover. The only way to unhang the cluster is by deleting the `cluster-name`-config config map, which also ends up deleting the original database.

This was originally discovered when attempting to spin up a Patroni cluster with only one node. When that one node dies, the new pod is unable to recover and hangs. Clusters with higher replica count will also encounter the same issue IF all pods go offline at the same time.

**Comment by jefkel** [comment]
In the event of all active DB nodes going offline at the same time and not processing fail-over between nodes, you do not want to have auto-heal enabled as this could result in a corruption of data.

Alternative methods for manual recovery are possible, but you will need to disable active patroni management while you manually recover the database.

https://patroni.readthedocs.io/en/latest/pause.html

At that point, you can start one of the nodes and work through manually recovering from the database outage.  Once you have successfully resolved your database issues and elected a new master, you can un-pause patroni to allow it to re-sync the replicas.

This is an advanced database recovery option, and requires some advanced postgres knowledge.
