### ISSUE TITLE
Base Aporeto policy Finalization in Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#134]
As an operations team member, we require a set of base network policies to be created and automated with the installation of the Aporeto platform inside of a cluster. These initial policies must ensure that the OpenShift platform continues to function for all core platform features. 

Continue to test existing policy against any alarms that are generated; adjust the policy as required. 
- [x] Finalize all OpenShift specific base policies
- [x] Determine the right network egress policy at different namespace levels 
- [x] Codify all policies
- [x] Verify policy by deploying a fully clean Aporeto namespace multiple times
- [x] Perform a policy code review with the team

**Comment by stewartshea** [comment]
Need to determine the right network egress policy at different namespace levels  - Want to ensure that teams can choose to NOT have internet egress access.

**Comment by stewartshea** [comment]
Successfully validated that a "deny egress" policy can be used at the openshift/namespace level in order to block egress internet traffic, 

![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/893f5fa3-d50a-4b69-bd47-b8e2cc2d4cd0)


```
I have no name!@grafana-22-mrf9p:/usr/share/grafana$ curl www.google.ca
curl: (6) Could not resolve host: www.google.ca
I have no name!@grafana-22-mrf9p:/usr/share/grafana$ curl https://8.8.8.8
^C

```

**Comment by stewartshea** [comment]
I'm waiting on a review with aporeto and would like our team to review on todays meeting.

**Comment by tosazuwa** [comment]
Hi @stewartshea , has this been reviewed by Aporeto yet? Whats their ETA?

**Comment by stewartshea** [comment]
Not yet, I pinged them again. I wouldn't let this be a blocker since we've
done extensive testing

**Comment by stewartshea** [comment]
Met with aporeto and went over the base policies; no issues stood out. We made 1 change to enable compressed tags and validated that we should be good to go with 8Gb RAM assigned to each enforcer in prod.
