### ISSUE TITLE
SPIKE- DXC Familiarization with Aporeto in Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#139]
As an operations team member responsible for the functionality of the OpenShift cluster, I would like to be familiar with the installation/removal & troubleshooting of the network policy toolkits. 

DXC to become familiar with the operational components of Aporeto as it relates to the platform operation: 

- [x] Understand troubleshooting methodology - [Doc](https://github.com/BCDevOps/platform-services/blob/aporeto/security/aporeto/admin/troubleshooting.md)
- [x] Deploy it multiple times
- [x] Run patch / upgrade / maintenance on nodes
- [ ] Write policy to solve issues after an upgrade
- [x] Remove and add enforcers from specific nodes 
- [x] Disconnect Lab from internet and verify enforcer recovery

*Feel free to add any additional items that seem natural to the above list*

**Comment by tosazuwa** [comment]
DXC Go-No Go decision By Monday Oct 1st to give enough time to familiarize with Aporeto in Lab.

FPO design pattern 1 testing in LAB currently.
