### ISSUE TITLE
Complete Policy Paperwork with Hosting / SecOps / DXC / DevEx

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#140]
As a platform-sevices team member, I would like to ensure that the necessary policies and paperwork exist to allow us to deploy the network security policy solution within the lab and production OpenShift clusters. 

- [ ] Sort out any necessary policy paperwork with the right teams;

**Comment by stewartshea** [comment]
@kelpisland @mitovskaol Feel free to update this card with the necessary tasks or teams that you need to interface with if it is appropriate to do so.

**Comment by tosazuwa** [comment]
@kelpisland @mitovskaol What teams do we need to be engaging with for required policy paperwork?

**Comment by mitovskaol** [comment]
STRA and PIA have been identified as the only assessments required to roll Aporeto out as an enterprise service. I am closing this ticket and the works on these assessments will be tracked in their corresponding tickets.
