### ISSUE TITLE
Namespace Hierarchy in Aporeto and Support Responsibility Assignment

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#141]
As many teams will be involved in defining and configuring network security policies, it is important to clearly outline which teams are accountable for which policies.
 
Document who is accountable for which policies at each "level" as it relates to the namespace hierarchy. 

Given the following namespace example; 
/bcgov-devex/ = Hosting Branch + SecOps
/bcgov-devex/platform-services/ = DXC + Platform Services 
/bcgov-devex/platform-services/production/ = DXC + Platform Services 
/bcgov-devex/platform-services/production/kamloops/ = DXC + Platform Services 
/bcgov-devex/platform-services/production/kamloops/ocp-cluster-name/ = DXC + Platform Services 
/bcgov-devex/platform-services/production/kamloops/ocp-cluster-name/team-namespace = Development Team

The above is just an example; this needs to be thought through, documented, and validated with all appropriate stakeholder teams.

**Comment by stewartshea** [comment]
Discussed today: 
- renaming the parent namespace from /bcgov-devex to /bcgov
- creating the non-platform-services assets in a "apps" child namespace

**Comment by mitovskaol** [comment]
@j-pye  Can you please update the ticket with the current namespace hierarchy that we have set up in Aporeto for documentation purposes. Thx!

**Comment by j-pye** [comment]
/bcgov/platform-services/production/kamloops/pathfinder/{licensePlate}-{dev,test,prod,tools}

This is an example of the namespaces that were set up with the aporeto install that took place yesterday, it matches the namespace structure that @stewartshea outlined in the body of the ticket. We still need to make clear where Non-OCP Namespaces will go.

We should probably get @NickCorcoran involved to help finalize who should get access to what namespace level.

**Comment by jleach** [comment]
We also have the lab:

/bcgov/test/lab-pathfinder-20191001

**Comment by stewartshea** [comment]
That one eventually needs to be destroyed and recreated in the proper path

**Comment by stewartshea** [comment]
No new update on this yet. I'll pick up the task this weekend and include the docs along with testing of the namespace management playbook.

**Comment by stewartshea** [comment]
See #401 for this

**Comment by mitovskaol** [comment]
Namespace hierarchy has been documented in #137.  Ownership/Control of namespaces has been identified for /bcgov namespace - corporate OCIO ISB, and at the application level - product teams. We will close the ticket for now and will create a new one when other groups express interest in taking ownership of other namespaces.
