### ISSUE TITLE
Production Rollout Plan Creation

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#144]
Document the anticipated rollout strategy and any anticipated impact to end user applications; this will be delivered once all final lab testing has been created. 

- [x] Complete cut-in cut-out process in lab multiple times
- [x] Document results
- [x] Review with Aporeto team and refine if necessary
- [x] Communicate plan

**Comment by stewartshea** [comment]
Initial rollout plan has been documented here; the automation playbook takes care of this but additional feedback is required on items like the desired cut-in time, communication plan, etc. 

https://github.com/BCDevOps/platform-services/blob/master/security/aporeto/rollout_plan.md


Looking for a review on this and to determine what else we might want to cover.

**Comment by stewartshea** [comment]
I feel like this can be closed.

**Comment by tosazuwa** [comment]
@stewartshea , i was about to ask the same. I will check with the team if any objections to the current plan in place, and if not, move to closed
