### ISSUE TITLE
Aporeto Production Rollout

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#145]
This EPIC captures all of the tasks / items required to get Aporeto deployed in production. 

Go-Live Day Prep Discussion took place on Monday, Oct 7, 2019 and the following decisions have been made:

1.	Communication plan
The announcement of the Aporeto Go-Live to the platform users will be posted on the platform service status notification’s page notifications – PR pending https://github.com/BCDevOps/platform-services-status-page-notifications/pull/19 followed by an announcement in the Rocketchat devops-alerts channel. An update will be posted in RC after the installation. 

2.	Existing applications: 
The playbook that installs the Aporeto enforcers in OCP PROD, will also automatically create an Aporeto namespace in the Aporeto Control Plan for each existing OCP namespace and add 3 base custom policies into this namespace - first that allows all pods to talk to Internet, second that allows all pods to talk to k8s API (for builds) and third that allows all pods to talk between themselves. 

This will allow the existing OCP applications to continue function “as is” and minimize the impact the Aporeto install will have on them. 

3.	New applications:
New applications onboarding into Openshift will be required to develop their own custom policies in order to open any communications for their app. 

4.	Custom policy development:
If an OCP application has a network access requirement that cannot be satisfied with the 3 base policies, the application dev team will contact the Next Gen Security team to seek assistance with developing a custom access policy. At this moment we can only support requests for ingress/egress communications between the OCP cluster and internet and within the cluster. All other requests that require connecting to the internal network Zones, or external infrastructure including public clouds will have to wait until after the security Pilots are complete (sometime in Q1 2020).

Developer's Quick Start Guide is being developed in the platform-services repo to assist teams with developing their own custom policies.

https://github.com/BCDevOps/platform-services/tree/feature/devdocs/security/aporeto/docs

5.	OCP 4.1 Upgrade 
During the upgrade to OCP 4.1, each existing OCP application will be required to develop a custom access policy , the 3 base policies will NOT be available by default anymore. Only those OCP applications that have custom access policies, will be migrated into the 4.1 Cluster.

**Comment by jleach** [comment]
@stewartshea @tosazuwa I think we can close this issue now - no? We're in prod and things are going well.

**Comment by tosazuwa** [comment]
Closing this now @stewartshea and @jleach
