### ISSUE TITLE
Document Support Model for Aporeto

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#146]
Document the Aporeto support model and details for all teams to be able to reference. The Operations teams will specifically require this documentation in order to collaborate with the vendor on operational support issues.

**Comment by stewartshea** [comment]
I've reached out to Ben from Aporeto to obtain this.

**Comment by stewartshea** [comment]
Support model PDF is currently posted here. 
https://github.com/BCDevOps/platform-services/tree/aporeto/security/aporeto/pdfs

**Comment by stewartshea** [comment]
@DanDeane @sbarre-esit  Does the support model doc meet your needs for this card?

**Comment by DanDeane** [comment]
I think it helps @stewartshea.  We may have a problem here though, where the platform has 24 * 7 support and the doc seems to only highlight support being Monday to Friday from 7am - 7pm.

**Comment by stewartshea** [comment]
There's likely a contingency required as a process for your team to leverage if something is network related. Not all of the tools that are deployed on the platform have 24*7 support, and so ultimately responsibility may fall on the platform services team. Not too sure. @kelpisland anyt thoughts here?

**Comment by mitovskaol** [comment]
Meeting with Dan Deane on Friday Sep 20 to discuss the operations support model for Aporeto in production.

**Comment by tosazuwa** [comment]
Hi @DanDeane , is there anyting you still require from the team for this ticket? Just checking to see if we can mark this as complete or there is still an outstanding task. Please advise

**Comment by tosazuwa** [comment]
Hi @kelpisland , did you have a chance to talk to Aporeto about extending their support window to 24/7? Please advise

**Comment by mitovskaol** [comment]
The support for Aporeto will be provided by the vendor between 7am-7pm Mon to Fri and by the BCDevOps platforms services teams outside of these hours and will leverage the current 77000 incident management process.
