### ISSUE TITLE
Aporeto breaks elasticsearch

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/platform-services#164]
The elastic search pods were failing to come up fully until the enforcer was removed.

**Comment by stewartshea** [comment]
Gog to re-test when I believe the enforcers are working properly

**Comment by stewartshea** [comment]
Redeployed enforcers with the latest version. 

Navigating to the Platform Tab we can see all the list of PUs: 
![image](https://user-images.githubusercontent.com/18314168/64198084-70f56200-ce3c-11e9-9164-904e9b261d0d.png)

**Comment by stewartshea** [comment]
In the OpenShift UI or via CLI we can also see the Aporeto PU (Processing Unit) details as they relate to the pod: 

![image](https://user-images.githubusercontent.com/18314168/64200112-ac922b00-ce40-11e9-8078-c5fb0a6b28b3.png)

**Comment by tosazuwa** [comment]
Hi @stewartshea , any new development on this issue?

**Comment by stewartshea** [comment]
This hasn't been reproduced and as such can be closed.
