### ISSUE TITLE
Integrate operator install into Aporeto install playbook

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#177]
The custom operator should be installed with the rest of the Aporeto components in #133. 
Create a set of playbook tasks that will install and remove the Aporeto operator.

- Create install tasks
- Create remove tasks
- Integrate into Aporeto install playbook

**Comment by stewartshea** [comment]
Need a couple of things here: 
- [ ] auth integration
   - use local user cred to generate temp token [this exists in the current deployment playbook]
   - create app credential with temp token
   - create secret for operator with app credential (creds.json) and config (default.yaml) in /opt/ansible/.apoctl
- [ ] set the default namespace in the default.yaml. (https://docs.aporeto.com/docs/main/references/apoctl/)
- [ ] remove the namespace spec / variable from the playbook
- [ ] modification for watching all namespaces

**Comment by stewartshea** [comment]
Smoke tested the operator in the lab (manually); 
- tested deleting a policy from the UI manually and the operator does reconcile it :)

**Comment by stewartshea** [comment]
@jleach noticed the operator currently installs the policy into the base namespace. this will need to be adjusted to the full path of each specific namespace.

**Comment by stewartshea** [comment]
Added code to the playbook for installing the operator and using an appcred and configmap in the operator to control scope of access. The following illustrates that the operator only has access to the aporeto namespace it has been installed into. 

```
bash-4.2$ apoctl api list namespaces -n /bcgov -o table -c ID -c name -c namespace
error 403 (bahamut): Forbidden: You are not allowed to access this resource. [trace: 1712bb86e254652f]
bash-4.2$ apoctl api list namespaces -n /bcgov/test -o table -c ID -c name -c namespace
error 403 (bahamut): Forbidden: You are not allowed to access this resource. [trace: 12b5e7136f74406e]
bash-4.2$ apoctl api list namespaces -n /bcgov/test/lab-pathfinder -o table -c ID -c name -c namespace

             ID            |                             name                             |         namespace           
---------------------------+--------------------------------------------------------------+-----------------------------
  5d71bf2f3561e000018bf973 | /bcgov/test/lab-pathfinder/advsol-ark                        | /bcgov/test/lab-pathfinder  
  5d71bf2c3561e000018bf96b | /bcgov/test/lab-pathfinder/advsol-mcs-test                   | /bcgov/test/lab-pathfinder  
  5d71bf343561e000018bf97b | /bcgov/test/lab-pathfinder/advsol-mon-dev                    | /bcgov/test/lab-pathfinder  
  5d71bf2c3561e000018bf96d | /bcgov/test/lab-pathfinder/advsol-mon-prod                   | /bcgov/test/lab-pathfinder  
  5d71bf353561e000018bf97f | /bcgov/test/lab-pathfinder/advsol-mon-test                   | /bcgov/test/lab-pathfinder 

```

**Comment by stewartshea** [comment]
@jleach the other two items on this card are for you to change. Once you've got the operator updated we can merge any of the manifest changes into the tree here: 

```
├── aporeto.yml
├── files
│   ├── bcgov-networksecuritypolicy-operator
│   │   ├── crds
│   │   │   ├── defenition.yaml
│   │   │   └── example-resource.yaml
│   │   ├── output
│   │   │   ├── apoctl_configmap.yml
│   │   │   └── operator.yml
│   │   ├── role_binding.yml
│   │   ├── role.yml
│   │   ├── service_account.yml
│   │   └── templates
│   │       ├── apoctl_configmap.yml.j2
│   │       └── operator.yml.j2

```
