### ISSUE TITLE
NetworkSecurity Policy CR User Testing

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#188]
As a platform operator, the following scenarios must be tested; 

- [ ] Developers should be able to easily create a NetworkSecurityPolicy custom resource with OpenShift Project admin or edit permissions

- [ ] Developers should NOT be able to create Aporeto specific custom resources

**Comment by j-pye** [comment]
@stewartshea what are you expecting as a deliverable for this? Just results, test plan with results, or ansible tests? Even if we don't add tests for this to a playbook now, I think we should add them eventually so tests can be repeated after Aporeto or OpenShift updates.

**Comment by stewartshea** [comment]
@j-pye just document the test results in the issue please.

**Comment by j-pye** [comment]
Admin and Editor permissions allow for the creation of Network Security Policy as expected.

I tried all of the aporeto resources and received forbidden when trying to view or create aporeto specific resources.

Going to call this a success.

**Comment by stewartshea** [comment]
Perfect, thanks!
--
Shea Stewart, Partner
Arctiq: Intelligent Architecture
shea.stewart@arctiq.ca
+1-647-972-5191
http://www.arctiq.ca
