### ISSUE TITLE
Complete an internal review of Security Exemption for Aporeto

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#197]
Aporeto implementation is not compliant with the existing corporate Network Security Standard and thus needs to follow the exemption process to be approved for implementing in production. 
 
A security exemption will need to be completed for Aporeto as part of the go-live prep plan.

**Comment by tosazuwa** [comment]
Exemption draft has been completed and pending team internal review. Once approved, we will send to the corporate security office for approval
