### ISSUE TITLE
Expose route to come to front end pod in OCP from outside

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#212]
Mutual certificate authentication between the Aporeto enforcer and JAG proxy – ice box, nice to have
 
Develop Aporeto network policy to allow communications between the pod as per design and don’t inherit the default policy
FPO app is installed in LAB,
 
Aporeto install – by default nothing can talk to nothing
Base policy – openb communications as they are now in openshift
Wade’s custom policy – open communications between the pods
 
SchemaSpy can only talk to DB in DEV and TEST. Wade should be able to start developing the network policy on Friday Sep 13.

**Comment by mitovskaol** [comment]
Duplicate of #171
