### ISSUE TITLE
As an MDS Developer, I want to securely connect to the existing Oracle Database in Zone B on Port 1521/1543 so that I can write an API service that will use (NRIS-Natural resource integration System) for integrating wit MDS system

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#213]
What we need from MDR team:
•	Test database or/access to team member w read/access to DB – 
•	assign a ticket to Clecio to create a test db in Calgary Zone B,
•	 Give Shea access to it. 
•	Clecio needs to work with the NMR DBA team to enable connection between the Aporeto proxy in Calgary Zone b to the database on exa data machine.

Test Plan /Acceptance Criteria – only NRM systems may connect/reach NRM databases (Aporeto tag = NRM?), non-NRM systems cannot connect.

Notes: 
•	NRM Miso people will control the Aporeto policy for the proxy in Calgary Zone B and will manually add any application that needs access to the database to that policy.
•	To connect to DB: you need to have a \ certificate and you need a credential (user name/pass).
•	In NRM subnet only NRM databases. Exa data machines for DB one in Kamloops and one in Calgary

Network setup:
Database DR site is in Calgary in Zone B, only OCP app DEV and Test can connect to DR site, OCP app PROD can only connect to PROD Database in Kamloops, DEV and TEST cannot talk to PROD DB. This can be achieved by checking the environment tag in the metadata generated by Aporeto.
Clecio already has 2 VMs in Calgary center and is waiting for 2 VMs for the data center in Kamloops. DXC has access to them (Stephen )

 Application Name: 
•	MDS namespace, app license plate = “empr-mds-prod”, -dev, -test
•	Name/email of ppl who need to see/admin to enforce policy = NMR MISO – Nick C.
•	Firewall is open for communication between OCP cluster and Calgary Zone B.
•	Aporeto does not need to encrypt communication between the OCP app and the DB, the DB will handle the encryption – an Oracle feature when connecting to the port 1543.
 
Test – a container in LAB OCP with SQL Plus to connect to the DB in Calgary Zone B.
 
Steps:
- [ ] Set up a container in LAB OCP with SQL Plus
- [x] Aporeto installed in LAB
- [x]  2 VMs installed in Calgary Zone B
- [ ] Aporeto enforcers installed on the VMs
- [ ]  Firewall port is open between the LAB cluster and Calgary Zone B
- [ ] Develop a custom Aporeto policy for the app in LAB OCP = outgoing policy
- [ ] Develop a custom Aporeto policy for the Aporeto in Calgary Zone B = incoming policy
- [ ] Test the allowed connection – query the DB in Zone B from SQL Plus in the container in LAB OCP.
- [ ]  Test the disallowed connections – try to connect to the DB from a non-NRM container.
- [ ]  Give access to Aporeto dashboard to the NRM MISO.

**Comment by mitovskaol** [comment]
Duplicate of 244, 243, 383, 389, 24`, 240, 384
