### ISSUE TITLE
Artifactory Installation in PROD

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#235]
A container for all activities related to installing and running Artifactory in OCP PROD cluster

**Comment by mitovskaol** [comment]
@caggles Can you please update this ticket with the high level overview of the work that has been done to install the Artifactory  OCP PROD cluster.

**Comment by caggles** [comment]
Artifactory has been installed in the prod cluster and is operational. Currently, there are 3 teams that have access for testing purposes.
