### ISSUE TITLE
Setup a test app in the LAB

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#241]
A test application/container with SQL Plus running in the LAB is needed to test connectivity from the OCP LAB platform to the DB server in Calgary Zone B.

**Comment by tosazuwa** [comment]
@cvarjao , can you confirm if this task is complete?

**Comment by cvarjao** [comment]
Done. Lab Cluster can reach enforcers on port 1543

**Comment by jleach** [comment]
When the VMs are provisiond and setup we'll just test by setting up a pod with CURL or making a network connection to the DB. No need to actually setup an app for this test.
