### ISSUE TITLE
Develop a custom Aporeto security policy for the LAB app and for the DB server in Calgary Zone B

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#244]
As an MDS Developer, I want to securely connect to the existing Oracle Database in Calgary NR Zone B on Port 1521/1543 from Openshift LAB cluster to test secure communications between the test app in the LAB and the Oracle database server in NRM Zone B in Calgary.

- [ ] Develop a custom Aporeto policy for the app in LAB OCP = outgoing policy
- [ ] Develop a custom Aporeto policy for the Aporeto in Calgary Zone B = incoming policy

**Comment by tosazuwa** [comment]
Moving this to Sprint 7 as there is a dependency on #383 being completed before this can be actioned
