### ISSUE TITLE
Develop and socialize Governance model

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#258]
Governance model has been developed and will be presented to the Product sponsor and governance committee at the inaugural governance committee meeting on Sep 30.

Tasks:
- [x] Develop governance model
- [x] Finalize a slide deck for governance committee
- [x] Finalize a deck for Sprint Review demo
- [x] Present the deck at the Governance Committee meeting 
- [x] Preset the deck at the Sprint 2 Review/Demo

**Comment by mitovskaol** [comment]
The Governance model has been presented at the Governance committee meeting on Sep 30, 2019
