### ISSUE TITLE
BCGov NetworkSecurityPolicy Operator Build Process

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#260]
As a maintainer of the BCGov NetworkSecurityPolicy operator, I would like fully automated and documented build pipeline for testing, building, and storing the operator. This process is currently manual and will not scale in the long term.

**Comment by mitovskaol** [comment]
@jleach  Looks like this is the duplicate of #216. Can you please have a look and if it is , close the ticket. Thanks.

**Comment by stewartshea** [comment]
This requires a couple additional tasks; 
- [ ] deployment into prod
- [ ] changes to build off of master 
- [ ] a build playbook to filter the webhook events from github

**Comment by jleach** [comment]
@stewartshea Re: Your additional tasks from Nov 27 above. I added a check/filter in the Jenkinsfile to only build the operator when changes are made within the operator directory structure (not every time someone commits to platform services). It builds of the master branch, and can be deployed to prod any time.

We still need to change the operator to watch for the `prod` tag and image changes.
