### ISSUE TITLE
BCGov NetworkSecurityPolicy Operator Credential Expiration / Refresh 

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#261]
The current implementation / install of the NetworkSecurityPolicy Operator generates an aporeto AppCred and stores it in K8S secret which we have seen expire. This expiration causes the Operator to fail to update policies... Either the expiration needs to be extended to be long-lived or we require a credential refresh.

The Aporeto Operator itself doesn't seem to have this issue, so it's possible that we can reach out to them to see how they've solved this challenge.

**Comment by stewartshea** [comment]
Further investigation required; currently the issue is not being experienced.

**Comment by stewartshea** [comment]
Will ask for comments from Aporeto before we close this off. Likely have this done next week.

**Comment by j-pye** [comment]
@stewartshea Did we ever hear back from Aporeto on this? Still an issue?

**Comment by stewartshea** [comment]
It's not an issue, I have a better explanation and will close this issue once I write out the documentation

**Comment by stewartshea** [comment]
See #401 for docs on this

**Comment by mitovskaol** [comment]
Documented here https://github.com/BCDevOps/platform-services/blob/master/security/aporeto/admin/auth.md
