### ISSUE TITLE
Procurement for CU

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#265]
Critical- To be completed by Oct 15th

**Comment by tosazuwa** [comment]
CU Procurement being reviewed currently by Legal team. ETA tentatively for end of Oct -more CU's procured

**Comment by tosazuwa** [comment]
Hi @lukegonis , any updates on this please?

**Comment by lukegonis** [comment]
RFQ is now live on BCBid, first intake period ends on Oct 21, at that point an SOW will be issued to vendors on the RFQ list, vendors will have one week to respond to the SOW.
