### ISSUE TITLE
Prep for Sprint Demo

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#269]
Record video of demo as backup plan if we cannot demo live

**Comment by stewartshea** [comment]
video is recorded, need to overlay audio and review with team

**Comment by stewartshea** [comment]
audio has been added, uploading now and will post the link when complete. Might find time to do another demo later today for "intra" namespace comms

**Comment by stewartshea** [comment]
Video is posted here: https://youtu.be/qWt9gtaHFQQ
