### ISSUE TITLE
Increase operator performance

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#273]
With the amount of policies that exist, the operator can't reconcile fast enough to provide a decent level of performance to end users. This is experienced in the manner in delay between creation of the `networksecuritypolicy` object and the actual policy creation within aporeto. In addition, deleting an object must wait for the actual policy to be removed from Aporeto, causing additional delay. 

When all policies are loaded we should perform some simple timing tests to set expectations: 
- [x] duration it takes to create the object **in aporeto** - ie. Time it takes for the network connectivity to function as expected
- [x] duration it takes to remove an object - ie. time the deletion command, as it will hang until the actual object is deleted

**Comment by stewartshea** [comment]
Scaling to multiple pods adds a resiliency benefit and does not add performance, as only one pod acts as leader.

**Comment by stewartshea** [comment]
Following the thread here: https://github.com/operator-framework/operator-sdk/issues/1714

Updated the deployment with `--max-workers=10` and moved to the latest (v0.10) of the Operator. v0.10 does not respect this flag but v0.8.2 does so we will stay with v.0.8.2. 

Testing with higher numbers of threads.

**Comment by stewartshea** [comment]
Moved to in-progress and self-assigned. This will be necessary for a production rollout.

**Comment by stewartshea** [comment]
4 cores and 25 workers has us running hot on an initial load of all policies

![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/d92dc5fa-2874-488b-a069-7dc35241e30e)

**Comment by stewartshea** [comment]
With ~ 170ish policies in place... 

```
[sheastewart@sheawei ansible]$ time oc delete networksecuritypolicy --all -n twistlock-defender
networksecuritypolicy.secops.pathfinder.gov.bc.ca "egress-internet-twistlock-defender" deleted
networksecuritypolicy.secops.pathfinder.gov.bc.ca "intra-namespace-comms-twistlock-defender" deleted

real    2m34.559s
user    0m0.526s
sys     0m0.090s
[sheastewart@sheawei ansible]$ 
```

We may want to determine if we want the finalizer added in here or not...

**Comment by stewartshea** [comment]
Changing the `reconcilePeriod` to `30m` for now has demonstrated better performance; 

The first CR removal was performed while the operator was still undergoing it's initial reconciliation from startup; the remaining 2 were tested after the operator had completed this initial reconciliation. 

```
[sheastewart@sheawei ansible]$ time oc delete networksecuritypolicy --all -n twistlock-defender
networksecuritypolicy.secops.pathfinder.gov.bc.ca "egress-internet-twistlock-defender" deleted
networksecuritypolicy.secops.pathfinder.gov.bc.ca "intra-namespace-comms-twistlock-defender" deleted

real    5m41.820s
user    0m0.358s
sys     0m0.059s
[sheastewart@sheawei ansible]$ time oc delete networksecuritypolicy --all -n steve-bla2
networksecuritypolicy.secops.pathfinder.gov.bc.ca "egress-internet-steve-bla2" deleted
networksecuritypolicy.secops.pathfinder.gov.bc.ca "intra-namespace-comms-steve-bla2" deleted

real    0m9.158s
user    0m0.331s
sys     0m0.040s
[sheastewart@sheawei ansible]$ time oc delete networksecuritypolicy --all -n steve-bla
networksecuritypolicy.secops.pathfinder.gov.bc.ca "egress-internet-steve-bla" deleted
networksecuritypolicy.secops.pathfinder.gov.bc.ca "intra-namespace-comms-steve-bla" deleted

real    0m8.567s
user    0m0.325s
sys     0m0.049s
[sheastewart@sheawei ansible]$ 
```

I think we are safe to leave the finalizer on for now as the playbook only takes 8-10s to run. 


It took roughly 6 minutes to reconcile the ~160 policies. 
![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/5a8e2e47-e0b2-4bb0-bda0-6c103b70fe47)

I'm going to increase the reconciliation period to 24 hours. I think twice a day should be good for now.

**Comment by j-pye** [comment]
Just curious, are we using a custom ansible config for the operator?

**Comment by stewartshea** [comment]
what do you mean specifically?

**Comment by stewartshea** [comment]
we aren't customising the ansible.cfg outside of what comes from the operator already. Is that what you're asking?

**Comment by j-pye** [comment]
That's exactly what I was asking. I was just curious since there are normally some basic ansible.cfg changes that can be made to speed up ansible start time, time per task, or template generation. I know they won't impact all of the actions you're referring to above but figured I'd check to see if we are already using something outside of the defaults.

**Comment by stewartshea** [comment]
Another test: 

```
[sheastewart@sheawei ansible]$ time oc delete networksecuritypolicy --all
networksecuritypolicy.secops.pathfinder.gov.bc.ca "egress-internet-devops-logging" deleted
networksecuritypolicy.secops.pathfinder.gov.bc.ca "intra-namespace-comms-devops-logging" deleted

real    0m11.551s
user    0m0.360s
sys     0m0.092s
[sheastewart@sheawei ansible]$ 
```

I feel this is acceptable for now.
