### ISSUE TITLE
Aporeto support model extension

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#278]
A concern was expressed about the current Aporeto support model that only covers M-F 7am-7pm.

A meeting is required with Aporeto to discuss the possibility to extend the support window to 24/7.

If it is not possible it impacts our ability to expand Aporeto beyond the Openshift cluster, it does NOT however impacts our Aporeto Production Roll-out for the Openshift cluster.

**Comment by stewartshea** [comment]
This meeting has taken place, all teams are aligned on current expectations and Aporeto will help identify at what size/scale they can offer higher levels of support to the BCGov. Currently we can proceed as-is with Aporeto deployed in the OpenShift cluster for our pilot users.
