### ISSUE TITLE
Process JINJA2 templates in memory for improved operator performance

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#279]
Currently we process our J2 templates and write them to disk. This can be optimized to make the operator more performant by processing the templates in memory.

**Comment by jleach** [comment]
This one is done. Waiting on other PRs to be merged before this one.

**Comment by stewartshea** [comment]
@jleach please rebase and then I can review

**Comment by jleach** [comment]
@stewartshea Ready.
