### ISSUE TITLE
Obtain external approvals for Aporeto Security Exemption

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#281]
The security exemption for Aporeto needs to be reviewed and approved by the corporate security office (Don C)

**Comment by tosazuwa** [comment]
Hi @mitovskaol , whats the status with the Aporeto security exemption? Its a blocker for APORETO STRA. Wont that be in turn a blocker for deploying APORETO in PROD?

**Comment by NickCorcoran** [comment]
Discussed with CITZ MISO and OCIO ISB - obtained agreement that no exemption is required.
