### ISSUE TITLE
Improve aporeto object naming convention

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#283]
Currently objects in Aporeto have a UID fixed to the end of a hard coded string like `custom-netpol-cdf432d`. This should be changed to use the hard coded string concatenated with the custom name chosen by the user. 

Example: `custom-netpol-api2db`

The UID will need to be moved into a metadata tag so that it can be used as part of the import label which will be `j2-template-name-UID`.

**Comment by jleach** [comment]
Waiting on other PRs to be merged.

**Comment by stewartshea** [comment]
PR's are merged @jleach - bring this one in when you're ready
