### ISSUE TITLE
Automated compliance audit checking on repos.

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#288]
This is an umbrella epic for all activities related to reinforcing compliance with STRA and PIA as part of the application development lifecycle as well as adding auto-remediation for the problems detected by monitoring software such as Aqua.

**Comment by jleach** [comment]
Implemented via [Issue 29](https://github.com/bcgov/repo-mountie/issues/29) in the repo-mountie repository. Unable to add to EPIC.
