### ISSUE TITLE
Identify performance metrics from Aqua for auto-remediation by Robo-Mountie

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#289]
Review the metrics provided by Aqua monitoring solution to identify those that could trigger actionable response by the Mountie, i.e. stop future deployments to production if a vulnerability is detected in a running container.

**Comment by jleach** [comment]
Based recent conversations it does not look like robo-mountie will be doing any sort of automatic remediation. Closing issue.
