### ISSUE TITLE
Should Aporeto openshift_project_exclusions include more projects?

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/platform-services#300]
How do we decide which projects to completely exclude vs just building policies for?

Some other infra projects are

- cns
- default
- kube-public
- kube-service-catalog
- logging
- openshift
- openshift-ansible-service-broker
- openshift-console
- openshift-infra
- openshift-metrics-server
- openshift-template-service-broker
- openshift-web-console

**Comment by stewartshea** [comment]
everything starting with `openshift` is now excluded by default. This was an addition to one of the later releases though I still have a few of them written into the profile for exclusion. What we have seems to work. 

At this point there isn't a complex decision making process around whether you want to use an exclusion or build a policy. The major consideration is whether or not we feel that we may want to see athe traffic flow of a specific item or we may want to add a security control mechanism to it.

**Comment by stewartshea** [comment]
The base deployment currently uses a set of exclusions, global namespace policies, or standard "basic user policies". If there is merit in chainging the configuration of this, it can be discussed and tested.
