### ISSUE TITLE
Split out network policy for OCP internal API

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#302]
Currently default policy is applied to every environment allowing all pods to talk to one another and the internet. This allows for existing environments to work as expected after Aporeto's deployment. If the default policy is removed by the environment owners they can no longer run deployments because the namespace can no longer talk to the OCP API.

It would be beneficial to split the OCP API into its own network security policy. This way teams that wish to secure their environment can delete two of the default policies but leave the OCP API policy in place so deployments work.

**Comment by jleach** [comment]
@stewartshea @j-pye FYI.

**Comment by stewartshea** [comment]
@jleach  I'll pick this up now since it's a quick one and ultimately should get in before the prod release
