### ISSUE TITLE
Evaluate End-User Access to Aporeto Console

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#305]
As a developer or a MISO, it is helpful to have dashboard where I can see all network security policies for my application, application network topology (history of all connection requests - incoming and outgoing) and have access to the audit logs. I would use this information to troubleshoot issues, conduct investigations or to ensure the application follow best security practices for network access configuration.

**Comment by stewartshea** [comment]
I quickly tested the "Platform Viewer" role and indeed the user see's much less than all of the features in the UI: 

![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/ab7d4fa5-b56d-41eb-a628-4b167ad79866)

**Comment by mitovskaol** [comment]
@j-pye  can you please look into the access model for the Aporeto control plane and present to the team so that we can figure out who will have access to it and what they should be able to see/do in the UI.

**Comment by j-pye** [comment]
I evaluated each of the roles and am looking forward to discussing it on Friday. (Moving to Review and Will close after leaving a note about the decisions made in Friday's meeting.

**Comment by mitovskaol** [comment]
The following design has come out of the discussion on Friday Oct 18,2019

1) Aporeto Control Plane (aka Console) will be used to create this dashboard.
2) A combination of 4 roles in Aporeto Console  - Network Viewer, System Viewer, Compute Viewer, Dashboard Viewer - will be used to provide VIEW ONLY access to the authorized users.
3) The dashboard will include the following data
  - application/namespace network security policy content
  - list of all processing units in the application/namespace - PU's tags and labels that together represent a PU identity.
 -  audit logs with the history of all changes to the policies
 - network topology - history of all connections for an app - incoming and outgoings - along with the status - whether it was allowed through the policy or denied.
4) Access to the Aporeto Console will be managed through a custom CRD  - named Network Policy Authorization in Openshift applications.
5) Access will be granted on a per OCP app/namespace basis.
6) Access implementation flow:
 - An app developer creates a custom resource from  Network Policy Authorization CRD and includes a list of email addresses for the users who should have access to the app namespace in the Aporeto Console.
7) BCGov custom operators picks up the change to the C
