### ISSUE TITLE
Aporeto Enforcer errors

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/platform-services#320]
While looking in the logs of an enforcer pod I'm seeing a lot of errors like this. Are these of concern?

> {"l":"error","t":1570054336.0325692,"c":"nfqdatapath/datapath_tcp.go:1125","m":"Failed to update conntrack table","app-conn":"142.34.217.48:142.34.217.48:45272:2379","error":"netfilter query: netlink receive: no such file or directory","errorVerbose":"netlink receive: no such file or directory\nnetfilter query\ngo.aporeto.io/enforcerd/vendor/github.com/ti-mo/netfilter.(*Conn).Query\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/github.com/ti-mo/netfilter/conn.go:58\ngo.aporeto.io/enforcerd/vendor/github.com/ti-mo/conntrack.(*Conn).Update\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/github.com/ti-mo/conntrack/conn.go:386\ngo.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/pkg/flowtracking.(*Client).UpdateNetworkFlowMark\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/pkg/flowtracking/flowtracking.go:60\ngo.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath.(*Datapath).releaseFlow\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/datapath_tcp.go:1117\ngo.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath.(*Datapath).processNetworkSynAckPacket\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/datapath_tcp.go:681\ngo.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath.(*Datapath).processNetworkTCPPacket\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/datapath_tcp.go:545\ngo.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath.(*Datapath).processNetworkTCPPackets\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/datapath_tcp.go:105\ngo.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath.(*Datapath).processNetworkPacketsFromNFQ\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/nfq_linux.go:87\ngo.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath.networkCallback\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/go.aporeto.io/trireme-lib/controller/internal/enforcer/nfqdatapath/nfq_linux.go:24\ngo.aporeto.io/enforcerd/vendor/go.aporeto.io/netlink-go/nfqueue.(*NfQueue).ProcessPackets\n\t/tmp/build/7be30de5/go/src/go.aporeto.io/enforcerd/vendor/go.aporeto.io/netlink-go/nfqueue/nfqueue.go:496\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}

**Comment by 0xmchadha** [comment]
No, these are not of concerns. They won't cause any communication or policy related failures. These essentially happen when the client or server has sent a RST packet and at the same time we are trying to update the conntrack entry. In the upcoming release we will be toning these error messages down.
