### ISSUE TITLE
Develop APORETO STRA

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#327]
- [x] Information Collection
- [x] Describe system from security lens
- [x] Create threat model
- [x] Conduct ISO and/or defensible security coverage assessment
- [x] Create Statement of Acceptable Risk (SoAR)
- [ ] Review with MISO and CIO
- [ ] MISO to obtain sign-off and submit to OCIO ISB

**Comment by NickCorcoran** [comment]
Conduct threat model and defensible security coverage assessment
Create Statement of Acceptable Risk (SoAR)
Review with MISO and CIO
MISO to obtain sign-off and submit to OCIO ISB

**Comment by NickCorcoran** [comment]
Items moved to new ticket for next sprint:
- [ ] Review with MISO and CIO
- [ ] MISO to obtain sign-off and submit to OCIO ISB
