### ISSUE TITLE
Develop a playbook to install Aqua Runtime Enforcement Agent

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#333]
[ ] Develop a YAML playbook to install a runtime enforcement agent for Aqua
[ ] Test the playbook in OCP LAB

Acceptance Criteria:
 [ ] code review for PR
 [ ] the Aqua enforcer is installed successfully

**Comment by j-pye** [comment]
This will carry over into Sprint 8. I have an email in with Aqua to see if there's a way to increase the agent log output.

Aqua Agent Pods are created on all of the Lab nodes successfully, however the agent is unable to connect to the aqua gateway from any of the nodes except for the storage nodes. I've tested and verified the aporeto network policies are not blocking connectivity.
