### ISSUE TITLE
Provision 2 VMs in OCP LAB cluster for Aqua Install

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#334]
An iStore order is required to provision 2 VMs in the OCP LAB cluster for installation of the new security tool  - Aqua. 

Luke, please let me know what details are required to complete the iStore order.

**Comment by mitovskaol** [comment]
iStore order was submitted on Monday Oct 7, 2019

**Comment by mitovskaol** [comment]
iStore order was approved on Oct 15, 2019

**Comment by j-pye** [comment]
Steven sent us an email on Monday, October 21st stating that the VMs were ready.

"OCIOPF-T-341 and 342 are build and ready to be used."

I have not yet tried to use either VM.
