### ISSUE TITLE
Install Aqua in LAB

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#336]
Run the playbooks to install and configure the Aqua components in the OCP LAB

Acceptance Criteria:
* Ensure Enforcers can enforce AQUA policies
* AQUA control plane is operational
* Validate high availability
* Cofig done as code
* Upgrade and uninstall functions

Components Working:
- [x] Agents
- [x] Console with HA
- [x] Gateways with HA
- [x] Operational + Audit Databases with HA
- [x] Scanner(s) and Scanner User Creation

**Comment by tosazuwa** [comment]
@j-pye , moved this to Sprint 4

**Comment by j-pye** [comment]
We're waiting on a Storage upgrade in the lab which currently has an ETA of tomorrow (Dec 11th)

**Comment by wmhutchison** [comment]
Recent testing in LAB for a full deployment reveals that the LAB infra nodes are all at 99% consumption of CPU Requests, thus not allowing all pods to be deployed and tested. 

Have filed an internal request with VMWare team to increase the vCPU of all three LAB infra nodes (no costs involved for increasing CPU on a VM, but we have to be able to prove we need it), expecting fulfillment to be done either next Monday or Tuesday (January 21st at the latest, will follow-up with VMWare team). 

A maintenance window will be scheduled to make the actual CPU adjustment once confirmed/approved (same-day RFC).
