### ISSUE TITLE
Install Aqua in PROD

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#337]
Run the playbook to install and configure Aqua components in OCP PROD cluster.

Aqua will be allowed to run during the "soak-in" period applying basic scanning policies without enforcement. Performance will be monitored closely during the soak-in period.

**Comment by wmhutchison** [comment]
Pending a final "go" decision to be announced this Wednesday (February 5th), we are currently anticipating a scheduled deployment of Aqua in PROD on Wednesday February 12th. The last due diligence today  is ensuring the PROD infra nodes have sufficient CPU/RAM capacity to hold the patroni database pods with the recommended values for CPU/RAM.

**Comment by j-pye** [comment]
Scheduled for Feb 26th @ 9AM

**Comment by j-pye** [comment]
I'm going to call this a success. We had a successful deployment of all components even though we had to remove aqua. Going to move this ticket to done and create new tickets for Aqua to upgrade and launch on OCP4.
