### ISSUE TITLE
Create Ops Alerting / Dashboard for Aporeto Enforcers 

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#341]
As an operator of the platform, I need a dashboard that will monitor the health of the enforcers as well and provide alerting. 

I would like to see a Sysdig dashboard and a webhook alert into Rocket Chat. We may also be able to create direct alerts from Apoerto into Rocket.Chat but it will take some scripting work on the Rocket.Chat side.

**Comment by stewartshea** [comment]
@sbarre-esit  I've created this dashboard for the lab; have a look and let me know if you want modifications (or add whatever you like :)) 

https://app.sysdigcloud.com/#/dashboards/133158/l:600?scope=kubernetes.cluster.name%20in%20(%22lab-pathfinder%22)

![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/387517e0-93d0-42ac-8fd4-6ec9830957da)

There are also a few alerts set up to dump into the lab-alerts channel; 

![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/03d50dcc-6650-4659-bbc7-62cb337b06c7)

Right now the alerts go to rocketchat, but we could also dump them to email.

**Comment by stewartshea** [comment]
Prod was created as well, just as an update

**Comment by sbarre-esit** [comment]
Sysdig seemed to be struggling in PROD to get data consistently.

![image](https://user-images.githubusercontent.com/24236108/66524429-4cc61a00-eaa7-11e9-9af6-4de4c7efadd7.png)
