### ISSUE TITLE
Create auto-generated STRA template with known details of platform

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#354]

**Comment by NickCorcoran** [comment]
Populated with details from OpenShift platform knowledge (including Aporeto, Aqua, KeyCloak, Vault, etc).  
If opinionated pipleline is leveraged, define starting controls/mitigation
Allow project team to select framework and products to be used
- If common frameworks/products are chosen, define controls/mitigation 
If common frameworks are NOT chosen, identify steps project team needs to take in assessing and engaging Ministry security team(s)
Generate starting place report for project team - provide copy on MISO dashboard?
- Can this be a living report that project team, security team can update? (probably not initially)
- Can this generate the SoAR?
