### ISSUE TITLE
Add wait for gov operator install and fix CRDs

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#359]
During deployment to prod we noticed an issue where the networksecuritypolicy crd wasn't installed correctly and the operator crashes, thus causing an issue for running the playbook since custom policies can't be created. 

Also add a wait_for state to validate the operator is ready and not crashing before moving on with the install. 

Acceptance Criteria: 
- [x] both externalnetwork and networksecuritypolicy CRDs are created and tested by the playbook
- [x] the operator has an appropriate healthcheck applied to it
- [x] the playbook waits to move on with it's tasks by verifying the operator isn't crashing.

**Comment by stewartshea** [comment]
also realized we don't have a health check on the operator. Need to add this in as part of this ticket.

**Comment by j-pye** [comment]
Update:
Testing this today and sending off to review.
