### ISSUE TITLE
remove cluster quota limits from aporeto projects

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#362]
during deployment we hit an issue where quota limits were hit as a result of automatic quota application during project creation. We need a task to validate that quota limits are not in place

**Comment by tosazuwa** [comment]
Hi @stewartshea , whats the priority of these bugs and who is working on them?

**Comment by stewartshea** [comment]
@tosazuwa I believe this should be assigned to @j-pye  - mostly since it's a minor change to the playbook and the fix will allow him to continue to be familiar with the playbook 

ultimately maybe @sbarre-esit should be a reviewer once it's complete

**Comment by tosazuwa** [comment]
@j-pye, are you okay to work on this bug? if yes, pls update what sprint and add estimates. And add @sbarre-esit  as a reviewer when its in test./review

**Comment by j-pye** [comment]
@tosazuwa can do.

**Comment by sbarre-esit** [comment]
I've got a playbook to manage all the quotas at https://github.com/bcgov-c/platform-ops/tree/master/playbooks/run/quota-applyer (haven't run it in a while). On my todo is to pipeline-ify it so it runs all the time.

For infra projects (where label `project_type != user`), all the quotas get removed and only one for storage is put in. https://github.com/bcgov-c/platform-ops/blob/master/playbooks/run/quota-applyer/tasks/apply-infra-quota.yaml

If you want to copy that quota into your playbook you should be good to go. https://github.com/bcgov-c/platform-ops/blob/master/playbooks/run/quota-applyer/quotas/infra-storage-quota.yaml

**Comment by j-pye** [comment]
PR: https://github.com/BCDevOps/platform-services/pull/458

I added the project_type label for when Steven's Quota Apply is pipeline-ified. 

@sbarre-esit Ready for your review when you have time.
