### ISSUE TITLE
High Level Design for the Robo Mountie (Security/Privacy Compliance Automation)

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#377]
As a developer, I would like tohave my application deployed in Openshift constantly monitored for vulnerabilities and get notifications if vulnerabilities are discovered ( in the future, the deployments that have a risk score that exceeds the pre-configured threshold should be stopped from deploying to production). In addition, every time the application is deployed, I would like to have it automatically checked for compliance with STRA/PIA controls.

- [ ] Finalize the technical architecture for the Robo-Mountie , aka Security/Privacy Enforcement Robot
  * the technology stack, the components, where they will be deployed and how signals will be consumed and enforcements actioned
 - [ ] Prioritize signals and their data source for integrating with the Robo-Mountie 

 ![Robo-Mountie.jpg](https://images.zenhubusercontent.com/5ae096c24b5806bc2bd09c0f/3dfb420b-fd08-4ef5-8396-2cccfe8332d8)

**Comment by tosazuwa** [comment]
meeting scheduled for Oct 24th. To update

**Comment by mitovskaol** [comment]
High level design decisions captured in the screenshot.
