### ISSUE TITLE
Provision and setup VMs in the data center in Calgary for RSI

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#380]
Assist RSI to get 4 VMs provisioned and configured for their Aporeto Pilot Project.

**Comment by jleach** [comment]
Information provided to Glen so they can order the apropriatly sized VMs. Need to get the order number to Stephen for tracking when done. I've asked Glen to send it to me.

**Comment by jleach** [comment]
Update: I think they are just trying 1 VM for the pilot.

**Comment by jleach** [comment]
They have received approval for a single test server (VM); iStore # 995027

**Comment by mitovskaol** [comment]
iStore order for professional services was opened on Oct 24 to install Aporeto on a single VM in JAG DMZ in Calgary.

**Comment by agahchen** [comment]
Hi @mitovskaol / @jleach .. is this the ticket tracking the aporeto enforcer installs for the RSI pilot?  Looking for the iStore order for that to update a sub-task in RSI-1403.

I understand that the VM (iStore 995027) has been procured.

Thanks!
David
