### ISSUE TITLE
Add Network Policy Authorization CRD to Operator - user access to Aporeto Console

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#382]
As a developer, I would like to control access to who can see network security policies for my application and be able to grant access to these selected people.

Access to the application namespace in the Aporeto Control will be controlled through a new Custom Resource Definition - Network Policy Authorization - that developers can add to their application in Openshift and include the list of emails for the people that should have access to VIEW the application network security policies in the Aporeto Console. 
The BCGov Aporeto operator will monitor the CRs and automatically provision access to the application namespace in the Aporeto Console. 
The users MUST have a GitHub ID that is part of BCDevOps organization.
The users will be assigned 4 roles in the Aporeto Console - Network Viewer, System Viewer, Compute Viewer, Dashboard Viewer . 

The dashboard will include the following data

* application/namespace network security policy content
* list of all processing units in the application/namespace - PU's tags and labels that together represent a PU identity.
* audit logs with the history of all changes to the policies
* network topology - history of all connections for an app - incoming and outgoings - along with the status - whether it was allowed through the policy or denied.

High level tasks:

 - [ ] Add new Network Policy Authorization CRD in Openshift 
 - [ ] Update the Operator to pick up the new Network Policy Authorization CRs and provision user access to the application namespace in Aporeto console based on the list of emails in the CR
 
Acceptance criteria:

- [ ] Add new Network Policy Authorization CRD to an application in Openshift  with a user email that matches a GitHub ID that is part of BCDevOps org.
- [ ] Access the Aporeto Console at https://console.aporeto.com and log in with the user GitHub ID.
- [ ] Verify that the user can view the namespace policies in the dashboard and all other info as listed above.

**Comment by jleach** [comment]
@stewartshea Any preference for the CRD name? ATM I'm using `AporetoConsoleAccess` in the attempt not to overload the word policy.

**Comment by jleach** [comment]
@j-pye @stewartshea Here is one issue I've run into: When creating policy the `import` function works like "replace if it exists" where as `create` works like you'd expect. The challenge will be in reconciliation: I have to be able to remove any users when they are removed from the CRD.

I think I'll just use the same technique of tagging the users (assuming its possible) with the k8s OID and during the reconciliation process (or update) I'll manually compute the diff and remove/add ppl as needed.

**Comment by j-pye** [comment]
@jleach Could you do the following on each CR Manipulation
- Generate a list of users from the CR
- Get the policy based on the target_namespace / policy name
   if the policy exists update it
   else create it. 
Then the users list would always be up to date on every CR manipulation without having to compute the diff because you passed in the entire user list so it'll replace the existing user list.

**Comment by NickCorcoran** [comment]
Conversation with OCIO ISB discouraged listing GitHub accounts as part of build to define access to the Aporeto web interface.  Suggestion is to leverage Keycloak and to allow use of IDIR, as there are many gov employees that may require this visibility, but may not want/need GitHub IDs.
This may require delay until Robo-mountie tooling is built out sufficiently to assist Keycloak definitions in authorization at the namespace level for each project. 
One example need for this is the MISO role in Ministries that will need to have visibility of all namespaces in their portfolio.  Do they need to be defined at each namespace, or is there a group access for all namespaces?  Something to consider.

**Comment by tosazuwa** [comment]
Imternal Meeting held: Wednesday Nov 13th

Decision: Here is a summary of the discussion about the access model for the Platform security tools (i.e. Aporeto Console) that took place today. We came up with a couple of assumptions that need to be verified by experts and tested. shea.arctiq and justin.pye please provide feedback on the feasibility of the approach. cvarjao please let us know if anything is missing in the description below.
1) Long-term approach to controlling the access to the Platform security tools is Verifiable Credentials.
2) Short-term - we would like to leverage the existing authentication path between KeyCloak and Aporeto Console to have KeyCloak inject authorization information (namespace name and role) into the JWT authentication token it received from IdP (GitHub) and pass it onto the Aporeto Console that (hopefully) can extract this information and automatically provision user's access to the namespace listed in the token when the user access it for the first time.
In order to turn it into self-serve service, we can develop a one-time script that will create groups in KeyCloak for all existing namespaces in Openshift and assign the admin role for that group to the namespace admin or the product owner. For the new namespaces, the creation of a KeyCloak group will be handled as part of the Openshift provisioning process. Once a user is set as an admin in the namespace group in KeyCloak, they can add other users to the group.
When KeyCloak receives an authentication token for Aporeto Console, it will extract user's GitHub account info from the token, check if the user is listed in any of the security groups in KeyCloak, and if yes, add the namespace info taken from the group description to the authentication token. And hopefully Aporeto can take it from there and automatically provision access to this namespace in Aporeto Console.

**Comment by mitovskaol** [comment]
As per decisions made in the meeting mentioned above, the approach outlined in this ticket is no longer relevant and the ticket will be closed.
