### ISSUE TITLE
Devhub Issue: Quick Start broken links

### ISSUE THREAD

**Issue by pdittaro** [BCDevOps/platform-services#395]
The samples link under the usage section is 404ing. As well, the text describing the directory as accompanying the document doesn't make sense without explicit inclusion of the directory in some fashion.

See below:
![image](https://user-images.githubusercontent.com/6808809/67314509-9b1ce500-f4b9-11e9-9364-5b98c3c4b6d9.png)

> path: (do not delete) https://github.com/BCDevOps/platform-services/blob/master/security/aporeto/docs/QuickStart.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Information-and-Application-Security/Quick-Start

**Comment by ShellyXueHan** [comment]
Dup of #399, closing
