### ISSUE TITLE
Devhub Issue: Quick Start [broken link]

### ISSUE THREAD

**Issue by andrea-williams** [BCDevOps/platform-services#398]
> path: (do not delete) https://github.com/BCDevOps/platform-services/blob/master/security/aporeto/docs/QuickStart.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Information-and-Application-Security/Quick-Start

## Devhub Content Issue
The Quick Start page contains a link to a "samples" directory but the dir is actually called "sample" in github, so following the link in the doc returns a 404.

**Comment by ShellyXueHan** [comment]
Dup of #399, closing
