### ISSUE TITLE
KeyCloak Login Pop-up UX issues

### ISSUE THREAD

**Issue by filiy** [BCDevOps/platform-services#4]
The pop up window from Keycloak to log in has some UX issues. 

- Buttons are small and close together, hard to use on mobile
- Lots of wasted space, maybe just make buttons bigger and move to top
- The window doesn't seem to re-size when the login re-directs to github, having to scroll down which isn't obvious

**Comment by ShellyXueHan** [comment]
Issues captured in https://github.com/bcgov/ocp-sso/pull/19. Waiting to be merged to SSO PROD.
@filiy instead of a pop up window, can it be a redirect to keycloak?
