### ISSUE TITLE
Ansible container needs additional space for processing CRs.

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#408]
The Ansible container of the custom operator is running out of space because 

```
Couldn't watch new directory /tmp/ansible-operator/runner/secops.pathfinder.gov.bc.ca/v1alpha1
/NetworkSecurityPolicy/gcpe-mygovbc-foodsafe-prod/
egress-internet-gcpe-mygovbc-foodsafe-prod/artifacts/8352103264063875156: 
No space left on device
```

```
$ oc set volume pod/networksecuritypolicy-operator-668b7c9d9-f7dft
pods/networksecuritypolicy-operator-668b7c9d9-f7dft
  empty directory as runner
    mounted at /tmp/ansible-operator/runner in container ansible
    mounted at /tmp/ansible-operator/runner in container operator
```

While it looks like the file system should have ~19G free it has a quota on EmptyDir set to 5G:

```
sh-4.2$ df -h /tmp/ansible-operator/runner
Filesystem                             Size  Used Avail Use% Mounted on
/dev/mapper/vgvarlog01-var_lib_origin   25G  5.8G   20G  24% /tmp/ansible-operator/runner
sh-4.2$ du -hs /tmp/ansible-operator/runner
4.2G    /tmp/ansible-operator/runner
```

**Comment by jleach** [comment]
@stewartshea Are you able to advise on how we should address this one? Should we update the playbook then re-run *and* manually edit the deployment YAML to add in a mount point? I don't see anything in Ansible's config allowing for the path to be specified (a bit surprising):

In [this operator document](https://docs.openshift.com/container-platform/4.2/operators/operator_sdk/osdk-ansible.html) they point to the [Ansible runner docs](https://ansible-runner.readthedocs.io/en/latest/index.html) to learn more about this directory.

**Comment by j-pye** [comment]
It relates to #362. 
Not sure if we want to remove the EmptyDir quota but we might be able to adjust it for the Aporeto projects. Thoughts?

Looks like there's a command to setup artifact rotation (see bottom of https://github.com/ansible/ansible-runner/blob/dbb078e601de47b14fe3ea4f6cdb83841430ddbb/docs/standalone.rst)

**Comment by sbarre-esit** [comment]
EmptyDir quota is done at the [node level](https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html#node-config-volume-config), not the project level. We need it in place to ensure users can't take down a node.

**Comment by jleach** [comment]
@j-pye Good find. Looks like [these docs](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/advanced_options.md) allow us to change `maxRunnerArtifacts` (default 20) to pear down what it keeps for each CR.

**Comment by jleach** [comment]
@sbarre-esit What do you think about my last comment? Should we mount a volume to /tmp and set `maxRunnerArtifacts` to something lower like 3? If so where does the fix go - in the playbook?

**Comment by sbarre-esit** [comment]
> Should we mount a volume to /tmp
Yes, to `/tmp/ansible-operator/runner` https://github.com/BCDevOps/platform-services/blob/master/security/aporeto/build/ansible/files/bcgov-networksecuritypolicy-operator/templates/operator.yml.j2#L73

> If so where does the fix go - in the playbook?
In the opertator template linked above. The template can also contain the PVC so that a volume is created to be used by the operator. Up to you how big you want to make it and how many old artifacts you want to keep.

**Comment by stewartshea** [comment]
I've pushed the change to the operator to reduce the amount of artifacts stored. Let's monitor this for a little while before we look at a PV. I'd rather not use a PV

**Comment by jleach** [comment]
Resolved and closing. No further issues with this.
