### ISSUE TITLE
Create Team DevOps Canvas'

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/platform-services#41]
Ideas of things to assess:

*   Product Owner:
*   Technical/Support Contact: Who to contact when there is something wrong with the app, and maybe causing some issues within the cluster
*   Team Composition: Employee, Contractor
*   Cloud Native Maturity: Ready > Friendly > Resilient > Native
*   CI/CD inplace?
*   12Factor
*   Time To Production (Average): End of every sprint, every other sprint , ...
*   Dependencies: DXC-Managed Database, IMB-Managed Database, IMB-Managed System, External-Database, External-System
*   How often is the application impacted by cluster maintenance/upgrade? Always, Sometimes, Not Impacted
*   DevOps Hand Book
*   ...

| Organizational Resource (People) | System Resource (Tools) | External Resources (Uncontrollable Variable) |
| --- | --- | --- |
| Team Structure | *** | *** |
| Team Knowledge | *** | *** |
| Numbers of Developers | *** | *** |

References:
- https://cloudplatformonline.com/rs/248-TPC-286/images/DORA-State%20of%20DevOps.pdf
- https://devops-research.com/assessment.html
[https://app.zenhub.com/files/155788763/208455dc-beec-4919-8c2a-f1661bab18b9/download](https://app.zenhub.com/files/155788763/208455dc-beec-4919-8c2a-f1661bab18b9/download)

**Comment by ll911** [comment]
developed questionnaires via monkey survey,  already sent out to all in general channel, can be sent out on a regular basis.
