### ISSUE TITLE
Aporeto training campaign

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#410]
Now that Aporeto is rolled out it would be good to educate teams that it exists and give a brief overview of what it can do. Specifically, demonstrate a simple use case like FPO. This should be part of the road show and geared towards teams running projects in the lab.

**Comment by jleach** [comment]
I brought this issue up with Stephanie and she tough it was good 👍. Talked to Diana also about what this might look like if we hosted something in the lab. To get the ball rolling we though about putting up a poster with some info about Aporeto being live.

**Comment by jleach** [comment]
@mitovskaol FYI.

**Comment by tosazuwa** [comment]
@Jleach. Are you saying this is a duplicate? Whats the ticket number for the existing ticket? i can add to the Product Backlog for SP next week

**Comment by mitovskaol** [comment]
@jleach Lets also discuss posting an announcement in one of the devops channels pointing to the Developer Guide and encouraging people to try it out and play with custom policies.

Also, need to talk to Clecio about mentioning the Guide in the Openshift 101 training.

**Comment by mitovskaol** [comment]
Duplicate of #464
