### ISSUE TITLE
Aqua STRA - Create Threat Model

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/platform-services#414]
Create threat model and report. 

- [x]  Draw model
- [x] Assess threat/risks for mitigation
- [x] Generate report

**Comment by NickCorcoran** [comment]
Diagramming out architecture for implementation in ThreatModeler.

**Comment by NickCorcoran** [comment]
Diagram verified with Justin.  Made some small adjustments.

**Comment by j-pye** [comment]
I'll also send you a screenshot of the aporeto network flow on my next deployment in case that's beneficial :)

**Comment by NickCorcoran** [comment]
@j-pye That would be great!
