### ISSUE TITLE
CPU quota based on requests

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/platform-services#42]
Investigate using quotas based on cpu `requests` and not just `limits`

**Comment by cvarjao** [comment]
Work has been done under https://github.com/bcgov-c/platform-operations-tools/pull/1

A message has beed posted on Slack #general channel in regards to this upcoming change.

**Comment by sbarre-esit** [comment]
New quota scheme applied to all `project_type=user` projects. No screaming so far.
