### ISSUE TITLE
Create a network join on the OCP level between OCP RSBC Hub (namespace id = jik2hd) and RSBC BI (namespace id = iowaey) namespaces in Dev and Test

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#426]
As a RSI pilot team member I need to be able to establish communication the RSBC Hub (namespace id = jik2hd) and RSBC BI (namespace id = iowaey) in Dev and Test so that pods in both name spaces can communicate in each environment (Dev to Dev, Test to Test). This communication will be controlled by an Aporeto policy but needs to be enabled on the platform level first.

**Comment by mitovskaol** [comment]
@stewartshea can you please review the instructions for this here https://github.com/bcgov-c/devops-platform-operations-docs/tree/master/custom-projects and let Steven know if they still stand.

**Comment by stewartshea** [comment]
Pretty sure this was complete?

**Comment by sbarre-esit** [comment]
Completed
