### ISSUE TITLE
Roadshow for Chief Digital Architect

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#429]
Book a presentation of the project for the gov's CDA and his team.

**Comment by tosazuwa** [comment]
Hi @mitovskaol @NickCorcoran , did this happen yet?

**Comment by mitovskaol** [comment]
@tosazuwa this didn't not happen yet and we dont have the date...moving it to the icebox.

**Comment by StephBacon** [comment]
We have not done this yet. I will look into organizing it.

**Comment by mitovskaol** [comment]
The project overview has been presented to the Digital Services Office team on Dec 18, 2019
