### ISSUE TITLE
Develop the PIA assessment form for Robo-Mountie

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#435]
As a developer, I want to make sure that I follow the corporate process for compliance with the personally identifiable information collection and would like to have the compliance check available as part of my production deployment.

Develop a web form to be added as a mandatory step in a production deployment pipeline. At the very first production deployment the product team will be asked to confirm that a standard PIA has been completed and provide the PIA number.  Once the PIA completion is confirmed, the production deployment can proceed. At the subsequent deployments , the web form will include questions to assess delta changes between the original data model and the new data model where it impacts PII collection.

To Be Determined: We will also evaluate a possibility to scan a data model stored in a project repo to assess the PII collection changes automatically.

**Comment by jleach** [comment]
I don't think this system will store or process any PI; it will probably just use some business contact info in the form of who the project admins are or what RocketChat channel they use.

Other than this, we're just going to be processing notifications from Aporeto (maybe), Aqua (probably), and GitHub (probably). These notifications will just contain network security policy, image vulnerability, or repo vulnerability information.

**Comment by jleach** [comment]
Deleted my last comment. Misread the subject.

**Comment by jleach** [comment]
After recent conversations on the OCP "registry" and a better understanding of repo-mountie / robo-mountie I believe this functionality won't be added to the bot.
