### ISSUE TITLE
Improving developer docs; update devhub indexing descriptions for aporeto 

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#439]
It is difficult to find the aporeto resources due to a lack of description or tags on the developer guide in devhub;

![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/8c9bd77d-bcf7-4e5b-b8d0-02603723276d)

We need to make this simpler and have more relevant links; https://developer.gov.bc.ca/topic/popular/Quick-Start for example is not specific as to what it is a quickstart for.

**Comment by stewartshea** [comment]
Moving this to review @mitovskaol and we can determine as a team if we're happy with the current state. I do think we may need to create a new card later for external networks

**Comment by stewartshea** [comment]
The site should rebuild today at some point and we should see the updated results.

**Comment by stewartshea** [comment]
![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/93cce51c-75f4-4f27-aa30-60e3b0ba7825)

**Comment by mitovskaol** [comment]
I also added the markdown files under aporeto/architecture folder to the DevHub search index so that they show up in the search results as well. Once DevHub is refreshed, we should be able to see them .

**Comment by stewartshea** [comment]
@mitovskaol  Well they shouldn't be added without proper descriptions or tags, and I don't see those yet. Maybe I'm looking in the wrong branch? I didn't see a PR with the indexing / description details.

**Comment by mitovskaol** [comment]
I am working on adding descriptions and metadata to the markdown files under aporeto/architecture.
The search indicies live in the bcgov/devhub-app-web/blob/master/app-web/topicRegistry/information-and-application-security.json file in DevHub repo.

**Comment by stewartshea** [comment]
ahh, got ya. That's what I was missing, you are still working on the other half.

**Comment by tosazuwa** [comment]
Hi @mitovskaol , @stewartshea , is this ticket done now? Please update

**Comment by stewartshea** [comment]
Looks like it to me - nothing else to add from myself on this. @mitovskaol anything else from you?
