### ISSUE TITLE
Write up proposed naming strategy for project sets

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/platform-services#44]
OpenShift project/namespace will be composed of an `identifier`, followed by `-` (literal), and a `suffix` where
- `identifier` is 6-characters long: Random mix of lower-case letters (a-z) and numbers (0-9)
- `suffix`: One of the following: `dev`, `test`, `prod`, `deploy`, and `tools`

**Comment by lukegonis** [comment]
@ShellyXueHan is this issue still blocked? Done? Or should we drop it?

**Comment by ShellyXueHan** [comment]
We are doing <6 digit license plate>-<env>
good to close now.
