### ISSUE TITLE
Update Openshift 101 training content with Zero Trust Model

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#442]
The content for Openshift 101 training needs to be updated with the reference to the new Zero Trust security model that has been enabled on the Platform as of Oct 9, 2019.  

An opportunity to socialize the Developer Guide for Custom Security Policy Developer available in DevHub at https://developer.gov.bc.ca/Trust-No-One

**Comment by stewartshea** [comment]
PR #43 addresses this. Sent to Patrick or Jeff for an approval

**Comment by stewartshea** [comment]
https://github.com/BCDevOps/devops-platform-workshops/pull/43/commits/e9cee875450aab5411b7fd87527128a6a08c35d4

**Comment by tosazuwa** [comment]
@stewartshea. Jeff confirmed he has reviewed this and i followed up with Patrick as well and he was on it.
