### ISSUE TITLE
Create a build and deploy process for the NSP backup CronJob.

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#453]
As a maintainer of the BCGov Aporeto instance, I would like my backup CronJob build and deployment process fully automated and documented.

**Comment by jleach** [comment]
Our new tools namespace `devops-security-tools` has been provisioned. Next steps are to setup the image build pipeline and schedule the cron-job to run in the `devops-security-aporeto-operator` namespace periodically.

**Comment by stewartshea** [comment]
@jleach I've integrated and deployed the cronjob in Prod. I had to make some changes and restructured the folder slightly, some of it was just running into fussyness with the github env var. Happy to run through the changes with you in case you disagree or if we want to talk about a higher-level strategy with the utils-container.
