### ISSUE TITLE
DevSecOps Workshop Preparations

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#464]
Content development and other preparation activities.

- [x]  Develop an ad 
https://www.eventbrite.ca/e/workshop-working-with-zero-trust-security-model-on-openshift-tickets-80167538265
- [x] Book a room
Alliance booked for Dec 2, 2019 9:30am-11:30am
- [x] Develop a slide deck
https://docs.google.com/presentation/d/1-RTIMLqc5lMpFPKIYFSLS0MlmvUDXROBQSvoMCWHl90/edit#slide=id.g73f14674b2_0_324
- [x] Prepare the demo environment
- [x] Run a survey

https://www.surveymonkey.com/results/SM-T29BZ2VS7/   pass "security"

**Comment by tosazuwa** [comment]
Can i close this? I just ticked the last task @mitovskaol
