### ISSUE TITLE
Add the Aporeto policy backup to the install playbook

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#468]
The backup CronJob is currently a OCP template that needs to be setup and configured manually. It would be better to have this setup and configured as part of the install playbook so all the Aporeto "components" are managed from a central location.

**Comment by jleach** [comment]
@stewartshea I've started moving this into the playbook in the branch `feature/cronjob-to-play`. I've moved the OCP template to be a j2 template and setup the necessary vars. Not sure what's next to wrap it up and test it.

**Comment by jleach** [comment]
The backups script currently uses its own image which is stored [here](https://github.com/BCDevOps/platform-services/tree/master/security/aporeto/scripts/openshift). We could add the tasks to build the initial image if it does not exists by converting the OCP template to j2.

**Comment by stewartshea** [comment]
I'm still working on this integration... at some point I need to restructure the whole playbook since there are so many components now. Currently I'm just focused on getting this deployed and scheduled.

**Comment by stewartshea** [comment]
Same note as #453; 
@jleach I've integrated and deployed the cronjob in Prod. I had to make some changes and restructured the folder slightly, some of it was just running into fussyness with the github env var. Happy to run through the changes with you in case you disagree or if we want to talk about a higher-level strategy with the utils-container.

**Comment by jleach** [comment]
@stewartshea I'm fine with with the changes. Shall we close this issue?
