### ISSUE TITLE
Operator performance improvements

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#472]
It's been observed that during a redeploy of the operator a full reconciliation will occur, which tends to be a blocking event to new requests for object management. For example, since we have finalizers, deleting an object will take 10 minutes or more to complete while the operator is running through the reconciliation tasks. This could affect when we want to deploy updates to the platform, which isn't ideal. This task for focus on whether we can schedule reconciliation in a more predictive manner and whether or not we can disable this activity during startup.

**Comment by stewartshea** [comment]
Moving this to in progress since I know @jleach was proposing some changes here.

**Comment by jleach** [comment]
Ya. I'll apply my changes once you're move of the operator dir is merged in.

**Comment by jleach** [comment]
Created PR #492 to address this by disabling the reconciliation period; I don't think its useful in our case.

**Comment by stewartshea** [comment]
@jleach Added a number of changes for PR#502

- changed reconciliation period from `0s` to `0`
- modified the dockerfile quite a bit
     - removed yum update (this causes every build to be long). If we feel we want this, then one possibly approach is to create a base image that updates the operator base image and then we build from that (though we can forego it for now)
    - Moved the playbook copy commands until after the USER 1001 layer so that the permissions are corrrect (the operator was actually failing on the last run)

I've tested this in the lab successfully. That said, I noticed on deployment that the Operator still tends to reconcile on startup. Something to look into.

**Comment by jleach** [comment]
@stewartshea Can we close this one? Looks like the PR is merged now.
