### ISSUE TITLE
Determine an appropriate way to store the AQUA reports.

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#523]
User story:
As a namespace admin I would like to have a single place for all security reports produced for my Openshift namespace. 

As per discussion captured [here](https://app.zenhub.com/workspaces/devsecops-5d545ae6999dd23f582aac62/issues/bcdevops/platform-services/156), AQUA scanning reports and GitHub vulnerabilities reports for each namespace will be stored in a namespace private repo in Artifactory.

- [ ] Develop a playbook to provision 600+ local repos in Artifactory
- [ ] Develop an operator that will extract namespace vulnerabilities from the general AQUA report and store the extract in the local repo
- [ ] Provision namespace admin with access to the local repo for their namespace

**Comment by caggles** [comment]
I had a discussion about the artifactory thing with @jefkel and he made the observation that using artifactory overcomplicates things - we could use, for example, a config map each namespace to store the output of the most recent report. Then we have rbac, we don't need to worry about adding another layer of maintenance, and it's more easily accessible (especially to non-technical team members).

**Comment by caggles** [comment]
closing as no longer relevant.
