### ISSUE TITLE
Formalize Aporeto support mechanism

### ISSUE THREAD

**Issue by jleach** [BCDevOps/platform-services#528]
From time to time we need support for Aporeto. Currently, the workflow is to mention our technical account manager (TAM) in RocketChat. This isn't ideal because he may not be in the office or otherwise available.

This ticket is to track formalizing the official support process for this product on our production system.

The Aporeto Escalation Procedure is available in Documize under the Protected content for Next Gen Security project ( privileged access required, contact @mitovskaol if you need access).
https://docs.pathfinder.gov.bc.ca/s/bn6v0ac6f9gue7hhirbg/protected-next-gen-security-project/d/bob3e34hpp5rkld1nuk0/aporeto-support-escalation-process

**Comment by mitovskaol** [comment]
A meeting booked on Jan 6 to discuss this with Aporeto.
