### ISSUE TITLE
Create a namespace for Aporeto network security policies for JAG Zone B components

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#531]
Set up namespaces in Aporeto console to store policies for JAG Zone B components in Kamloops and Calgary

`/bcgov/apps/jag/non-prod/kamloops`
`/bcgov/apps/jag/non-prod/calgary`
`/bcgov/apps/jag/prod/kamloops`
`/bcgov/apps/jag/prod/calgary`

The list of users with access to these namespaces will be communicated out-of-band.

**Comment by j-pye** [comment]
@mitovskaol  Should JAG be AG? I thought their name had changed?

Also, should the users provided have access to write policy in all 4 of those NS or just non-prod?

**Comment by j-pye** [comment]
Complete. 
Users have been added and namespaces have been created
