### ISSUE TITLE
Statuspage configure without rocketchat alert

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/platform-services#534]
I do not always want the rocket.chat alert sent from the status page when running the *configure* activity of the statuspage.yml  playbook.  Specifically when recovering from a deployment issue.

**Definition of Done**
The statuspage.yml will have an option (or activity) to run the configure activity without the rocketchat announcement.

**Comment by stewartshea** [comment]
added a variable `rc_notify` default to yes. It can be passed as an extravar to be set to `no`. Also added a `manual_deploy.sh` script in the ansible container which defaults to no for the deployment of app manually.
