### ISSUE TITLE
Create and publish a log of team events

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/platform-services#540]
- [x] Track, document and socialize workshops, roadshows, stakeholder engagements that the team is involved. What is happening and what is coming up.

- [ ] Add to the Project Overview page  and keep updated a list of all roadshow session conducted for the project and planned

**Comment by mitovskaol** [comment]
@tosazuwa  I believed you started working on this, how far along are you with compiling the list of all completed roadshows?

**Comment by tosazuwa** [comment]
Completed already. Here is the document link:

https://drive.google.com/a/bcdevexchange.org/file/d/1vFK0fMR4q62WDsArriPcx6eG1MBc4kes/view?usp=sharing

**Comment by tosazuwa** [comment]
Any decision on how we want socialize the info for upcoming events? @mitovskaol @bevmcphee
