### ISSUE TITLE
Profile doesn't auto-populate email address

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/platform-services#6]
After signing up with GitHub and going into My Account -> Profile ,  the email address is unset. Shouldn't RC be able to pull that info from GitHub?

![image](https://user-images.githubusercontent.com/24236108/50188799-a884a400-02d7-11e9-831a-9cde7a3be9c3.png)

**Comment by filiy** [comment]
This should be covered by Reggie now. Over to Shelly to confirm and close out.

**Comment by ShellyXueHan** [comment]
Covered by keycloak with first broker login and required actions for existing users.

**Comment by ShellyXueHan** [comment]
To be tested.

**Comment by filiy** [comment]
Can we close this @ShellyXueHan ?

**Comment by ShellyXueHan** [comment]
yes.
