### ISSUE TITLE
Move bcgov-c/devops-platform-workshops to bcdevops

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/platform-services#64]
Making workshop/training materials more widely available, and accessible to anybody.

**Comment by stewartshea** [comment]
I'll get this done

**Comment by mark-walle** [comment]
Any update on this?

**Comment by cvarjao** [comment]
They both have been transferred:
- https://github.com/BCDevOps/devops-platform-workshops
- https://github.com/BCDevOps/devops-platform-workshops-labs
