### ISSUE TITLE
Automation of KeyCloak realm provisioning

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/platform-services#67]
Currently, the process of provisioning new KeyCloak realms is manual, driven by requests in slack, which are manually actioned by DevOps Team Services humans.

Furthermore, there is a review process required for production use of the BCeID identity provider that is currently manual and disconnected from the provisioning process.

We would like to improve the situation by providing a mechanism for development teams to provision realms in an automated, self-service model. The creation of realms should be completely automated, with an improved, but not automated mechanism for managing access to the production BCeID identity provider.

Some notes have been captured in an existing [GitHub issue](bcgov/reggie#24).

A new repository or (repositories) will be created in bcgov once active development begins and issues will be tracked there.

**Comment by jleach** [comment]
@ShellyXueHan This is in progress - no?

**Comment by ShellyXueHan** [comment]
@jleach yes work is happening at https://github.com/bcgov/realm-o-matic . Good to close this one.
