### ISSUE TITLE
Request resolution of DNS lookup error for burden.idir.bcgov (JHI-1282)

### ISSUE THREAD

**Issue by agahchen** [BCDevOps/platform-services#684]
Request resolution of DNS lookup error for burden.idir.bcgov .

**Comment by agahchen** [comment]
Part of epic #172.

**Comment by sbarre-esit** [comment]
Opened INC0035518 to have someone from network look into this.

**Comment by sbarre-esit** [comment]
DNS record exposed on the DMZ resolvers.

Please test and confirm.

**Comment by agahchen** [comment]
Confirmed that burden.idir.bcgov is now resolvable on Pathfinder.

Thanks Steve!
