### ISSUE TITLE
Profile image link to Gravatar

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/platform-services#7]
Is it possible to do an automatic import of a gravatar.com image based on the registered email address to a rocketchat user profile?

### Manual steps to link to Gravatar image

I was unable to generate the same md5hash of my email address as the gravatar website does, but if you go to https://en.gravatar.com/site/check/{your_email_address} it will display a page that shows the gravatar generated email hash for that profile (if it exists).  Using the URL generated with the hash in the rocketchat profile worked to pull the profile image.

https://www.gravatar.com/avatar/{md5hash_from_gravatar_site}

**Comment by filiy** [comment]
@jefkel This happens automatically already. If you go to Rocket Chat user profile you should see your Gravatar image
