### ISSUE TITLE
Status Page Showing Incorrect Data

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#708]
The status page is showing service unavailability for a few internal and external services that appear to be up. 

![image](https://user-images.githubusercontent.com/18314168/89933641-59dafa80-dbdd-11ea-99e4-a172b8d812a4.png)

Need to investigate further the status showing in Prometheus DB and whether changes to blackbox  or prometheus need to be made.

**Comment by stewartshea** [comment]
Testing has revealed that this is a result of the blackbox exporter image update to 0.17.0 from the previous 0.16.0. 

Placed the exporter into debug mode to gather additional detail. 
```
        - command:
            - /bin/sh
            - '-c'
            - >-
              /bin/blackbox_exporter --log.level=debug
              --config.file=/etc/blackbox_exporter/config.yml
```

Opened up this issue: https://github.com/prometheus/blackbox_exporter/issues/672

Reverting to 0.16.0 for now.

**Comment by stewartshea** [comment]
Resolved the issue by updating the configmap to fix the HTTP2 valid version (`http/2.0`)

**Comment by stewartshea** [comment]
logging elasticsearch is still showing down which appears to be unreleated to the above configuration issue

**Comment by stewartshea** [comment]
@wmhutchison  the other services should be reporting correctly now. The Elasticsearch service will report as down until the route is fixed. It looks to be misconfigured at this point in time, and while people don't use that route, this system needs to query it for the health of the ES cluster. We can either fix the route (which you will need to do) or we pull it from the monitoring list.

**Comment by wmhutchison** [comment]
@stewartshea I have fixed the routing issue, and issued an internal ticket for adding this to our Openshift upgrade documentation workflow since it's likely that the breakage of this route is taking place during OCP upgrades. Once documented, this issue should no longer come up going forward.

**Comment by stewartshea** [comment]
Thanks @wmhutchison ! It looks to be reporting correctly now.
