### ISSUE TITLE
Investigate PV monitoring

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#710]
As a platform user, I would like to be able to monitor the free space of my persistent volumes in OpenShift. Is this possible with sysdig. 

**Definition of Done**
Investigate the Prometheus metrics exposed to sysdig (or other hots metrics), in order to determine if PV usage can be reported on. Document the findings if this is or isn't possible. 

**Additional context**
It's clear that filesystem usage can be reported on via the sysdig agents, but aren't clear whether PV's are reported on.

**Comment by stewartshea** [comment]
We are able to get the kubelet prom metrics into the dashboard, but I suspect it's coming in as a host metric which may be hard to apply a scope to. 

![image](https://user-images.githubusercontent.com/18314168/90583632-a3f44b00-e19e-11ea-8510-76e533bccea9.png)

**Comment by stewartshea** [comment]
In addition to the above concern, we also need to determine how to better filter out specific prom metrics as to not saturate or hit the configured limit.

**Comment by stewartshea** [comment]
In addition to the above concern, we also need to determine how to better filter out specific prom metrics as to not saturate or hit the configured limit.

**Comment by stewartshea** [comment]
I've reached out to Sysdig about how to best handle scoping these resources down to individual teams. The thinking right now is that each app team requires *2* sysdig teams, one scoped to the kubernetes pods/deployments/etc and one to their PV's. It's not ideal, but it should work.

**Comment by dleard** [comment]
Hi @stewartshea, do you have a timeline estimate for when we will be able to monitor PV's with sysdig? I have come up with a stop-gap solution for my team using an airflow DAG and we're trying to decide if it's worth it to implement it in the meantime.

**Comment by stewartshea** [comment]
@dleard it's likely a couple weeks before I can get this feature in place, barring any unforeseen blockers

**Comment by dleard** [comment]
Thanks! I'll pass that info along to my team.

**Comment by stewartshea** [comment]
This feature build is in-progress. I'm just working out some new processes to use the new sdc-cli tool rather than the API since the API for new dashboards has been deprecated by Sysdig.

**Comment by stewartshea** [comment]
Here is a mock up of the storage dashboard; I'm still working on the operator changes to build this upon team creation, followed by an update of the docs. 

![image](https://user-images.githubusercontent.com/18314168/94292687-42f12d00-ff2b-11ea-8cd2-a04cd99e2e65.png)

**Comment by dleard** [comment]
looks great, thanks for the updates & your work on this @stewartshea!

**Comment by stewartshea** [comment]
This feature has been released in https://github.com/BCDevOps/platform-services/pull/719

@dleard have a look and let me know what questions come up (in rocketchat) and we can fix up the docs to make sure they support new users of this feature.

**Comment by stewartshea** [comment]
With this feature released, I am going to close this issue. I will open another issue specific to the netapp-file-standard reporting issues.
