### ISSUE TITLE
Rocket.Chat route for http://chat.pathfinder.gov.bc.ca throws 503/"application not available" and does not redirect when accessed using *http*. It should redirect to *https* automatically/transparently.

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/platform-services#72]
Rocket.Chat route for http://chat.pathfinder.gov.bc.ca throws 503/"application not available" and does not redirect when accessed using *http*. It should redirect to *https* automatically/transparently.

**Comment by filiy** [comment]
@sheaphillips Added `insecureEdgeTerminationPolicy: Redirect` to the route. Tested and working. Deploy template updated. 

Closing.
