### ISSUE TITLE
netapp-file-standard not reporting utillization to kubernetes. 

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#722]
**Is your feature request related to a problem? Please describe.**
`netapp-file-standard` PVCs do not report utilization in the `kube_volume_*` promtheus metrics endpoints. This makes it impossible for teams to alert based on PVC utilization. This was observed in openshift 3.11. We haven't yet checked OCP4. 

**Definition of Done**
PVC's using this storage class are reported in the kubelet metrics and accessible via prometheus & sysdig.

**Comment by stewartshea** [comment]
Ran a test in our new OCP4 lab cluster and all netapp file based storage classes are working properly. At this point, since OCP3.11 will be decommissioned, I'm not sure it's an issue that is worth fixing on these clusters. 

```
$ oc get pvc  --all-namespaces | grep netapp-file  | grep shea
shea-test                  test                                         Bound     pvc-b8ffee3f-bb14-497c-b39b-99590e2ee141   1Gi        RWX            netapp-file-standard    4m50s

```
![image](https://user-images.githubusercontent.com/18314168/94713235-85927b00-0318-11eb-981f-a6713da921f6.png)


@sbarre-esit thoughts?

**Comment by sbarre-esit** [comment]
Agreed, not worth fixing.

**Comment by matthieu-foucault** [comment]
`kubelet_volume_stats_available_bytes{namespace="0fad32-dev"}` does not seem to return any result on sysdig, when looking either in `0fad32-team-persistent-storage` or `0fad32-team`. Same issue for our other namespaces.

@sbarre-esit @stewartshea are there more steps required on your side for netapp-file-standard and netapp-block-standard usage metrics to be available in sysdig, or am I the one missing some steps?

cc @pbastia @dleard @Maralsotoudehnia @Dianadec

**Comment by stewartshea** [comment]
@matthieu-foucault  I'll have to dig deeper into this, we were focused on getting the team operator deployed but didn't dig deeper into the file / block reporting differences. I'll let you know what we find.

**Comment by ShellyXueHan** [comment]
@matthieu-foucault you should be able to see PVC metrics from `[license-plate]-team-persistent-storage` team dashboard now. Please double check and update, thanks!

**Comment by matthieu-foucault** [comment]
@ShellyXueHan I can confirm that it works, thanks! I tried different namespaces and sysdig teams and I can see usage for both file and block storage.
