### ISSUE TITLE
User registration/login tests (rocketchat)

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/platform-services#76]
Test cases for signup to walk through all the way to signed in to rocketchat:

The following tests need to be completed with each of the 4 user types: IDIR, BCeID, GitHub (bcgov org member), GitHub (no org memberships)

- New user to Keycloak, no rocketchat
- Existing keycloak user, no info updated, no rocketchat
- Existing Keycloak user, updated info (no email verification), no rocketchat
- Existing Keycloak user, email validated, no rocketchat
- existing keycloak user, with rocketchat (should be the final happy state)

**Comment by ShellyXueHan** [comment]
I've tested the flows.

TODO: disable keycloak account linkage feature.

**Comment by ShellyXueHan** [comment]
After Keycloak upgrade, will retest the flow. Closing the ticket for now.
