### ISSUE TITLE
Patroni image doesn't have rsync

### ISSUE THREAD

**Issue by mark-walle** [BCDevOps/platform-services#77]
Performing:
```
$ oc rsync --no-perms=true ./ caps-pgsql-dev-3-0:/home/postgres
WARNING: cannot use rsync: rsync not available in container
# [ ... list of files in working directory... ]
Ignoring the following flags because they only apply to rsync: --no-perms
```
The files from the working directory _do_ transfer, but not by `rsync`.

**Comment by stewartshea** [comment]
personally I don't see this as an issue. My suggestion is to close rather than install rsync into the tool unless someone can provide a reason as to why they need rync.

**Comment by mark-walle** [comment]
`oc rsync` is a useful tool for copying database archives to and from our pods for backup and restore purposes; we do exactly that in our GDX Analytics CAPS project (at least for now).

[The documentation](https://docs.openshift.com/container-platform/3.11/dev_guide/copy_files_to_container.html#copying-basic-usage) states that the `oc rsync` tool "is built into the CLI". I took that to mean that under normal circumstances a warning message would be a deviation from the expected behaviour. I just _expected_ it to work as documented without warnings. It has worked for me in the past on other pods without warnings; this was the first time I saw that.

despite the warning, the files still manage to transfer to and from our pods. I am not sure what `oc` is doing to work around the rsync being unavailable here and functionally accomplish the same thing.

**Comment by WadeBarnes** [comment]
@mark-walle, May I suggest using the [backup-container](https://github.com/BCDevOps/backup-container) for backups.  There are a couple projects that I know of using it to backup Patroni based databases, one of which is SSO.  We use it heavily in the VON projects.

**Comment by lukegonis** [comment]
@mark-walle any updates on this?

**Comment by mark-walle** [comment]
@lukegonis No updates: the warning when running rsync persists.

**Comment by jefkel** [comment]
@mark-walle closing this issue for the following reasons:
- rsync is not a requirement for a running postgres DB
- manual update functionality is present through oc tool (with appropriate warnings, but still functional)
- Recommended approach for backup/restore for databases can be leveraged through the backup-container referenced above which will avoid the issue/warning you're finding.

Note: Closing this issue does not preclude incorporating community developed solutions in the future via PR.
