### ISSUE TITLE
Existing users not auto invited to new default rooms

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/platform-services#80]
when creating a default room, the existing users do not get notified/invited to join the room. For now, need to run `/invite-all-from #general` to invite all users (as #general has been default for the whole time and contains all users).

**Comment by filiy** [comment]
@ShellyXueHan I don't really think this is a concern. We probably won't be adding many default channels going forward. If we do than just use the /invite-all. 

Can we close thos?

**Comment by ShellyXueHan** [comment]
@filiy Yes, let's make sure this is documented somewhere reminding that we need to run `/invite-all` when creating new default channels. And that should be good enough!
