### ISSUE TITLE
Rocket Chat Integrations (webhooks) access

### ISSUE THREAD

**Issue by filiy** [BCDevOps/platform-services#83]
Right now all users have access to create api tokens for their own user. They don't have access to manage their own Integrations ( incoming/outgoing webhooks) should they? Or should there be an Integrator role that we only give people that need it?

**Comment by filiy** [comment]
Giving all users access to manage their own, will review shortly too see if being abused.

**Comment by jleach** [comment]
I think this is done - ya? I was able to create a Webhooks for TFRS.

**Comment by filiy** [comment]
Yup this is done now.
