### ISSUE TITLE
warning connect.session() memorystore

### ISSUE THREAD

**Issue by filiy** [BCDevOps/platform-services#9]
This error is coming up when starting the Rocket Chat pods.
```
Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.
```
Not sure if this is a concern, I cannot find any documentation on the Rocket Chat site. I did find some info about this error around general NodeJS usage.

https://digitalrizzle.wordpress.com/2013/04/26/mongodb-fix-connection-session-memorystore-is-not-designed-for-a-production-environment/

https://github.com/keystonejs/keystone/issues/3478#issuecomment-333564259

https://github.com/RocketChat/Rocket.Chat/issues/10714

https://www.npmjs.com/package/memorystore

**Comment by filiy** [comment]
I just need another set of eyes on this before I close it, or if a concern then dig deeper.

**Comment by ll911** [comment]
RocketChat need to choose a set of memory store for sessions
https://github.com/expressjs/session/issues/556 and should be patched by RocketChat

**Comment by filiy** [comment]
Going to close this. Don't believe this needs any action from us.
