### ISSUE TITLE
Feature Request: /remindme

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/platform-services#94]
SlackBot supported /remindme that would DM you a reminder of something at a time. Could we get something similar added to RC?

**Comment by caggles** [comment]
I'm going to start taking a look at this when I can!

**Comment by caggles** [comment]
hey steven, fyi, there is a semi-working version of a bot that does this on rocket.chat right now!
if you'd like to test it, jump into a DM with the "testbot" user and try one of these commands:
`testbot rc version`
`testbot what time is it?`
`testbot remind [me/username] in <time in minutes/hours/days/weeks>  to <action>`

Keep in mind that testbot is currently being actively worked on, so it may not always work properly and, right now, the reminders are not persistent, so they'll disappear after every restart of the service (which happens a lot right now). But it is available for you to try if you'd like to play with it!

**Comment by sbarre-esit** [comment]
Would be nice if `testbot help` existed to list commands it recognizes?

Any chance we can eventually use it in channels instead of via DM?

**Comment by caggles** [comment]
At the moment, I have it running on a private channel during testing because I don't want to issue a command and have it accidentally ping everyone on #general or something. That's something I plan to change once it's more ready for release :)

I'll look into a testbot help command as well!
